### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by thanksyouall**

### CODE REVIEW

**Review by onesimple-team — APPROVED** [review]

**Review by bouncycatt — CHANGES_REQUESTED** [review]
wdwedwe

**Review by onesimple-team — APPROVED** [review]
- [x]

**Review by onesimple-team — APPROVED** [review]
fdsfsd - [x] I checked docs.

**Review by onesimple-team — APPROVED** [review]
fdsfsd 
- [x] I checked docs.

**Review by bouncycatt — APPROVED** [review]
dkwmwkwskddsm
- [x] I checked docs
- [x] I checked docs
- [ ] - [x] I checked docs

**Review by VofSwords — APPROVED** [review]

**Review by VofSwords — APPROVED** [review]
- [x] I checked docs

**Pull request closed without merging**
